# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Meta
tagline:          'A Jekyll theme'
description:      '<h4 style="color:white;font-size:14pt">咩塔</h4>努力點技能樹的老工程師'
#url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
#  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
#  repo:           https://github.com/poole/hyde
