# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Meta
tagline:          '筆記本'
description:      '<h4 style="color:white;font-size:14pt">咩塔</h4>努力點技能樹的老工程師<br /> <font size="3">布衣青山坳 樓台小聚早</font><br /><font size="3">月如腰 琴指搖 醉時狂歌醒時笑'</font>
#url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
#  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
#  repo:           https://github.com/poole/hyde
